export const ErrorCodes = {
    // Generic
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    CONFLICT: "CONFLICT",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    // Category
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
    // Brand
    BRAND_NOT_FOUND: "BRAND_NOT_FOUND",
    BRAND_ALREADY_EXISTS: "BRAND_ALREADY_EXISTS",
    // Product
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    PRODUCT_ALREADY_EXISTS: "PRODUCT_ALREADY_EXISTS",
    PRODUCT_OUT_OF_STOCK: "PRODUCT_OUT_OF_STOCK",
    // Auth
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
};
//# sourceMappingURL=error-codes.js.map